image: docker:20.10.23

stages:
  - build
  - test

services:
  - docker:20.10.23-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cp .env.template .env

docker-build-wrapper:
  stage: build
  tags:
    - docker
  script:
    - GITLAB_ACCESS_TOKEN=${CI_JOB_TOKEN} docker compose build
    - docker compose push

tests-integration:
  stage: test
  image: docker:20.10.23-dind
  tags:
    - docker
  script:
    - GITLAB_ACCESS_TOKEN=${CI_JOB_TOKEN} docker-compose up -d
    - docker exec /mods-interface-simphony_server-1 sh -c "pytest"
  after_script:
    - docker compose rm -vsf
