image: docker:20.10.23

stages:
  - build
  - test

services:
  - docker:20.10.23-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - cp .env.template .env

docker-build-wrapper:
  stage: build
  tags:
    - docker
  script:
    - IMAGE_TAG=$CI_REGISTRY_IMAGE/$CI_BUILD_REF_SLUG:wrapper-agent-$SIM_CMCL_MODS_WRAPPER_VERSION
    - docker info
    - source .env && docker build --build-arg GITLAB_ACCESS_TOKEN=${CI_JOB_TOKEN} --build-arg YML_FILE=$YML_FILE --build-arg EXTRA_INDEX_URL=$EXTRA_INDEX_URL --target production -t $IMAGE_TAG  .
    - docker push $IMAGE_TAG

tests-integration:
  stage: test
  image: docker:20.10.23-dind
  tags:
    - docker
  script:
    - GITLAB_ACCESS_TOKEN=${CI_JOB_TOKEN} docker-compose up -d
    - docker exec /mods-interface-simphony_server-1 sh -c "pytest"
  after_script:
    - docker compose rm -vsf
